### ISSUE TITLE
Mismatch on provider type in UI and resource for OIDC integration

### ISSUE THREAD

**Issue by elumalaigjfrog** [jfrog/terraform-provider-platform#102]
When importing a platform_oidc_configuration  resource which was manually created in Artifactory using UI, the provider is imported as     "provider_type": "Generic OpenID Connect" which is against the provider values as per the documentation. 

[provider_type](https://registry.terraform.io/providers/jfrog/platform/latest/docs/resources/oidc_configuration#provider_type) (String) Type of OIDC provider. Can be generic or GitHub.

```terraform
terraform {
  required_providers {
    platform = {
      source = "jfrog/platform"
      version = "1.8.0"
    }
  }
}

provider "platform" {
  url   = "https://arturl/artifactory"
  access_token = "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}

resource "platform_oidc_configuration" "my-github-oidc-configuration" {
  name          = "testneww"
  description   = "My GitHub OIDC configuration"
  issuer_url    = "https://token.actions.githubusercontent.com"
}
```

```console
# import % terraform import platform_oidc_configuration.my-github-oidc-configuration testneww
platform_oidc_configuration.my-github-oidc-configuration: Importing from ID "testneww"...
platform_oidc_configuration.my-github-oidc-configuration: Import prepared!
terraform {
  Prepared platform_oidc_configuration for import
platform_oidc_configuration.my-github-oidc-configuration: Refreshing state... [name=testneww]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

```console
import % cat terraform.tfstate
{
  "version": 4,
  "terraform_version": "1.9.0",
  "serial": 1,
  "lineage": "be705437-e831-3ffe-6d5e-b9f36cad9802",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "platform_oidc_configuration",
      "name": "my-github-oidc-configuration",
      "provider": "provider[\"registry.terraform.io/jfrog/platform\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "audience": "test-github",
            "description": "test",
            "issuer_url": "https://token.actions.githubusercontent.com",
            "name": "testneww",
            "provider_type": "Generic OpenID Connect"
          },
          "sensitive_attributes": []
        }
      ]
    }
  ],
  "check_results": null
}
```

Artifactory Version:     "version": "7.88.0",

Terraform version : 1.90

Terraform provider version:   version = "1.8.0"

**Expected behavior**

The imported provided type should be generic or github

**Comment by alexhung** [comment]
@elumalaigjfrog Thanks for the report. This is curious as `provider_type` is a required attribute and your resource does not have it. And yet, there is no error in the import process.

**Comment by jgrumboe** [comment]
Hi @alexhung 
I
@elumalaigjfrog opened that issue because of my support case. I'd leave the non-erroring Import aside (isn't that working as designed by TF Import process?).
The more imported thing is that the UI sets a `provider_type` of "Generic OpenID Connect", although valid values are only "generic" or "Github".
This leads to an change in the next apply and later to an inconsistency with the UI. The UI shows then the value "generic" as selected in the drop-down.

**Comment by alexhung** [comment]
@jgrumboe Looks like Terraform doesn't error out for import when the configuration is missing required attribute. I wonder if this is a bug or intentional.
