### ISSUE TITLE
Error while installing jfrog/platform v1.8.2: checksum list has no SHA-256

### ISSUE THREAD

**Issue by mgr110** [jfrog/terraform-provider-platform#111]
**Describe the bug**
When trying to upgrade the jfrog/platform provider from `1.8.1` to `1.8.2` I get the error: `Error while installing jfrog/platform v1.8.2: checksum list has no SHA-256`.  The Artifactory version is `7.77.11` and also fails on the Jfrog cloud platform.

I am using Terraform version `1.9.2`. The bug can be reproduced by running `terraform init` with the following configuration:
``` tf
terraform {
    required_providers {
        platform = {
            # https://registry.terraform.io/providers/jfrog/platform/latest
            source  = "jfrog/platform"
            version = "<2.0.0"
            }
    }
}
```

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

**Expected behavior**

**Additional context**

**Comment by NiklasRosenstein** [comment]
I just ran into the same issue. The SHA256SUM listed in the GitHub release is

```
6f5d31c7e23c3c279bdc092da3e6f548e09e51d28252e73c92088ca1f3d55264  terraform-provider-platform_1.8.2_darwin_arm64.zip
```

But 

```
❯ curl  'https://github.com/jfrog/terraform-provider-platform/releases/download/v1.8.2/terraform-provider-platform_1.8.2_darwin_arm64.zip' | shasum -a 256
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

**Comment by alexhung** [comment]
@mgr110 @NiklasRosenstein We recently switched to the Terraform Registry Org beta program and I suspect it may be the issue. 11.2.0 is the first version to be published after migrating to the beta program. Nothing on our side with regards to the packaging or signing of the provider has changed.

Looks like TF registry has not updated their copy of the checksum file due to file name parsing issue on their side.

**Comment by alexhung** [comment]
@mgr110 @NiklasRosenstein HashiCorp is aware of this issue. They've manually fixed the issue for Artifactory provider and will be working on the same for this provider.

They have also identified the issue on their side and are working on a fix.

**Comment by alexhung** [comment]
HashiCorp has resolved the issue with this release. I've verified I can install 1.8.2 now.

They have also identified the issue on their side and are working on a fix.

**Comment by mgr110** [comment]
The TF registry had not updated their checksums correctly, as mentioned in this [issue](https://github.com/jfrog/terraform-provider-mission-control/issues/12). 1.8.2 can now be installed.
