### ISSUE TITLE
Licence Management with the provider

### ISSUE THREAD

**Issue by Zwordi** [jfrog/terraform-provider-platform#12]
Hello,

I would like to present an feature request about the license management.

Currently we are using mainly TF & IaC to manage our Artifactory stack.
We do have a need about the license management.

Based on https://jfrog.com/help/r/jfrog-rest-apis/install-license an POST is available to push a new license to the API that will then push it on local nodes.
On the endpoint there is no attributes available to check the content of the installed license like an hash of the license file.
We do have the expiration date of the license but it’s not enough to think about a way to do it with TF right away.

The resource would be very close to the **property_set** with an adaptation towards the endpoint target and the actions.

Based on the artifactory stack I think that doing something at the sdk level would be more consistent however I think that posting on this project is more consistent. 
A new functions like [CheckArtifactoryLicense](https://github.com/jfrog/terraform-provider-shared/blob/main/util/sdk/sdk.go#L225) would be a good startpoint from my perspective.

Resource related I think that this new resource would need to have attribute like:
* name
* license_key/license_file (to be able to load it through a string or an file functions)

Then once created we would have those new attributes like:
* type: Entreprise
* valid_until
* licensed_to

What do you think ? Am I clear enough ?

Spoilers : I’m no go developer :)

**Comment by alexhung** [comment]
@Zwordi I released v1.2.0 with new resource `platform_license` to manage single license. Currently the API has limitation that prevent me to create a resource to support managing HA license.
