### ISSUE TITLE
Adding AWS IAM role API

### ISSUE THREAD

**Issue by trahim** [jfrog/terraform-provider-platform#122]
**Is your feature request related to a problem? Please describe.**
Ability to to create AWS IAM roles in this guide for the jfrog operator all via the provider https://jfrog.com/help/r/jfrog-installation-setup-documentation/configure-jfrog-platform-for-passwordless-access-to-eks

**Describe the solution you'd like**
AWS IAM Role resource and data type.

**Describe alternatives you've considered**
No functionality so no alternative with the provider.

**Comment by alexhung** [comment]
@trahim This is in our Q3 plan so will be available in next few weeks (probably sooner).
