### ISSUE TITLE
Missing MyJFrog API Token warning when not specified

### ISSUE THREAD

**Issue by mymasse** [jfrog/terraform-provider-platform#132]
**Describe the bug**
When not specifying the deprecated `myjfrog_api_token` in the provider configuration or using `JFROG_MYJFROG_API_TOKEN` environment variable a warning will be printed all the time.

***Sample configuration***

```hcl
terraform {
  required_version = ">= 1.0"  
  required_providers {    
    platform = {
      source  = "jfrog/platform"
      version = "1.12.0"
    }
  }
}

provider "platform" {
  url          =  <VALID URL>
  access_token = <VALID ACCESS TOKEN>
}
```

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

***Versions***
Artifactory: 7.90.13
Terraform: 1.9.6
Provider: 1.12.0

**Expected behavior**
If this argument is deprecated why even print a warning if not used.

**Additional context**
N/A

**Comment by alexhung** [comment]
@mymasse Deprecating an attribute is a multi-steps process. The first step is to mark the attribute as 'deprecated' whilst retaining all functionality. The next step is to remove functionality with next major release whilst keeping the attribute in the provider config schema. Then final step is to remove the attribute altogether in another major release.

So expect the warning message be gone in next major release.

**Comment by zamanh** [comment]
Why should this be seen for those who aren't using that provider causing this warning?
