### ISSUE TITLE
platform_permission should accept empty sets

### ISSUE THREAD

**Issue by mgriffin13** [jfrog/terraform-provider-platform#142]
**Is your feature request related to a problem? Please describe.**
I'm attempting to migrate from the deprecated `artifactory_permission_target` into the `platform_permission` and I'm running into an issue with how `platform_permission` models the data.

In Terraform, I have a list that describes the permission targets I want:

```
locals {
  repo-targets = {
   proj1 = {
       repos  = ["repo1", "repo2"]
       groups = ["group1", "group2"]
       users  = ["svc1", "user1"]
    },
    proj2 = {
       repos    = ["repo3"]
       groups   = ["group3"]
       rw_users = ["svc2"]
    },
  ]
}

resource "artifactory_permission_target" "repo-permissions" {
  for_each = local.repo-targets

  name = "repo-${each.key}"

  repo {
    repositories     = each.value.repos
    includes_pattern = ["**"]

    actions {
      dynamic "groups" {
        for_each = toset(lookup(each.value, "groups", []))
        content {
          name        = groups.value
          permissions = ["read", "write", "delete", "annotate"]
        }
      }

      dynamic "users" {
        for_each = toset(lookup(each.value, "users", []))
        content {
          name        = users.value
          permissions = ["read", "write", "delete", "annotate"]
        }
      }

      dynamic "users" {
        for_each = toset(lookup(each.value, "rw_users", []))
        content {
          name        = users.value
          permissions = ["read", "write", "annotate"]
        }
      }
    }
  }
}
```

Not every target will have a users or groups block, but it'll have at least 1. I'm trying to convert the `users` and `groups` blocks to a straight list like this:

```
resource "platform_permissions" "repo-permissions" {
  for_each = local.repo-targets

  name = "repo-${each.key}"

  artifact = {
    targets = [ for repo in each.value.repos :
      {
        name = repo
        include_patterns = ["**"]
      }
    ]

    actions = {
      users = [ for user in lookup(each.value, "users", [] :
        {
          name = user
          permissions = ["READ", "WRITE", "DELETE", "ANNOTATE"]
        }
      ]
    }
  }
}
```

The issue is that if `users` is empty, then Terraform errors stating that "Attribute artifact.actions.users set must contain at least 1 element, got: 0"

**Describe the solution you'd like**
Allow an empty set to be treated the same as a null set. This would emulate the previous behavior using the dynamic operator

**Comment by alexhung** [comment]
@mgriffin13 Have you tried using `null` in place of `[]` for the `lookup()` func default value? Terraform treats `null` the same as unset for value, IIRC.

**Comment by alexhung** [comment]
@mgriffin13 Got it! I'll remove the empty list validation.
