### ISSUE TITLE
Manage xray meta permission missing

### ISSUE THREAD

**Issue by Osazz** [jfrog/terraform-provider-platform#150]
**Describe the bug**
In `artifactory_permission_target` resource `[managedXrayMeta](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/permission_target#managedXrayMeta)` permission was one of the one supported and during migration to `platform_permission` this error 

```
 ╷
 │ Error: Invalid Attribute Value Match
 │ 
 │   with platform_permission.permissions,
 │   on main.tf line 19, in resource "platform_permission" "permissions":
 │   19: resource "platform_permission" "permissions" {
 │ 
 │ Attribute
 │ artifact.actions.groups[Value({"name":"builders","permissions":["ANNOTATE","MANAGE","MANAGEDXRAYMETA","READ","WRITE"]})].permissions[Value("MANAGEDXRAYMETA")]
 │ value must be one of: ["WRITE" "MANAGE" "SCAN" "DELETE" "READ" "ANNOTATE"
 │ "EXECUTE"], got: "MANAGEDXRAYMETA"
```

From Artifactory Permission UI, I can still select Manage Xray Meta

![Image](https://github.com/user-attachments/assets/9cff9b39-36c1-468e-9661-f56ecbe968cd)

- Artifactory Version : "7.99.2"
- Xray Version: "3.106.7"
- Terraform version: 1.9.8

```
resource "platform_permission" "my-permission" {
  name = "my-permission-name"

  artifact = {
    actions = {
      users = [
        {
          name = "my-user"
          permissions = ["READ", "MANAGEDXRAYMETA"]
        }
      ]
    }

    targets = [
      {
        name = "my-docker-local"
        include_patterns = ["**"]
      }
    ]
  }
}

```
**Expected behavior**
Able to create permission with `managedXrayMeta`

**Comment by Osazz** [comment]
In this documentation https://jfrog.com/help/r/jfrog-platform-administration-documentation/select-users-and-assign-permission-actions ManageXrayMeta is still allowed Permission too

**Comment by alexhung** [comment]
@Osazz Thanks for the report! Looks like the resource needs to be updated to include this (and any other new) permissions.

**Comment by alexhung** [comment]
@Osazz My apology. The `managedXrayMeta` value in the `artifactory_permission_target` resource is now `SCAN` in the `platform_permission` resource.
