### ISSUE TITLE
Plan shows changes `platform_oidc_identity_mapping` on each run.

### ISSUE THREAD

**Issue by nbaju1** [jfrog/terraform-provider-platform#153]
**Describe the bug**
`terraform plan` shows changes to `platform_oidc_identity_mapping` on each run, without any changes to configuration.

Terraform code in JSON as a result of `cdktf synth`:

```json
    "platform_oidc_identity_mapping": {
      "platform_entra-id-oidc-mapping_DBF343FA": {
        "//": {
          "metadata": {
            "path": "jfrog/platform/entra-id-oidc-mapping",
            "uniqueId": "platform_entra-id-oidc-mapping_DBF343FA"
          }
        },
        "claims_json": "{\"roles\": [\"jfrog_user\"]}",
        "description": "Entra ID OIDC user mapping used for client setup",
        "name": "entra-id-user-mapping",
        "priority": 1,
        "provider_name": "${platform_oidc_configuration.platform_entra-id-oidc_C34CCD09.name}",
        "token_spec": {
          "audience": "jfac@*",
          "username_pattern": "{{preferred_username}}"
        }
      }
```

Output:
```
  # platform_oidc_identity_mapping.platform_entra-id-oidc-mapping_DBF343FA will be updated in-place
  ~ resource "platform_oidc_identity_mapping" "platform_entra-id-oidc-mapping_DBF343FA" {
      ~ claims_json   = jsonencode( # whitespace changes
            {
                roles = [
                    "jfrog_user",
                ]
            }
        )
        name          = "entra-id-user-mapping"
        # (4 unchanged attributes hidden)
    }
```

Terraform 1.9.8
Platform provider 1.16.0
Artifactory version: 7.100.2

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

**Expected behavior**
Plan showing no change to identity mapping

**Comment by alexhung** [comment]
@nbaju1 This is not unexpected behavior. To ensure the JSON string is valid, the resource converts the JSON string into Golang `map` type first before being converts to JSON as part of the API request. We recommend using the `jsonencode` function to set the `claims_json` attribute to ensure repeatability.

**Comment by nbaju1** [comment]
@alexhung since we use the CDKTF with Python, we don't have access to that function. Here is the Python snippet for this resource. Any suggestions?

```Python
OidcIdentityMapping(
    self,
    "entra-id-oidc-mapping",
    name="entra-id-user-mapping",
    description="Entra ID OIDC user mapping used for client setup",
    provider_name=entra_user_oidc.name,
    priority=1,
    claims_json=json.dumps({"roles": ["jfrog_user"]}),
    token_spec=OidcIdentityMappingTokenSpec(
        username_pattern="{{preferred_username}}",
        audience="jfac@*",
    ),
      )

**Comment by alexhung** [comment]
@nbaju1 I think the `indent` arg may allow you to adjust the formatting of the json output to match.

**Comment by nbaju1** [comment]
@alexhung I circumvented the issue and simply did `claims_json='{"roles":["jfrog_user"]}',` for now. Thanks for the pointer!
