### ISSUE TITLE
Support for new `ldap_group_settings` field in `platform_saml_settings`

### ISSUE THREAD

**Issue by gira0** [jfrog/terraform-provider-platform#154]
**Is your feature request related to a problem? Please describe.**
In the artifactory 7.98.7 self-hosted release new field was added to manage the groups of saml users via ldap. I would like to configure the field using terraform. 

**Describe the solution you'd like**
Be able to configure the setting with this provider

**Describe alternatives you've considered**
Currently manually set the settings via API

**Additional context**
See also the saml documentation here for this setting: https://jfrog.com/help/r/jfrog-platform-administration-documentation/enabling-synchronization-of-ldap-groups-for-saml-sso

**Comment by alexhung** [comment]
@gira0 Thanks for the suggestion! I've added this to our plan.
