### ISSUE TITLE
realm attributes should not be read only on `platform_group` resource

### ISSUE THREAD

**Issue by piotrminkina** [jfrog/terraform-provider-platform#159]
**Is your feature request related to a problem? Please describe.**
I'm using `realm` and `realm_attributes` attributes to preconfigure groups that comes from LDAP. This way I can then use references to these groups when defining permissions using the `platform_permission` resource. With the spin-off of the `platform_group` resource to the `artifactory_group` resource, why can `realm` attributes no longer be configured?

**Describe the solution you'd like**
I would like that as in resource `artifactory_group` the attribute `realm` and `realm_attributes` could still be configurable.

**Describe alternatives you've considered**
This is probably the best solution so far.

**Additional context**

Example of my usage:

```hcl
resource "artifactory_group" "ldap_publishers" {
  name             = "art.publishers"
  description      = "Publishers of the Artifactory app"
  auto_join        = false
  admin_privileges = false
  realm            = "ldap"
  realm_attributes = "ldapGroupName=art.publishers;groupsStrategy=STATIC;groupDn=cn=ART.Publishers,ou=Applications,ou=Groups,[...]"
}

resource "platform_permission" "anything" {
  name = "Anything"

  build = {
    targets = [
      {
        name             = "artifactory-build-info"
        includes_pattern = ["**"]
      },
    ]
    actions = {
      groups = [
        {
          name        = artifactory_group.ldap_publishers.name
          permissions = ["READ", "WRITE"]
        },
      ]
    }
  }
  artifact = {
    targets = [
      {
        name             = "ANY"
        includes_pattern = ["**"]
      },
    ]
    actions = {
      groups = [
        {
          name        = artifactory_group.ldap_publishers.name
          permissions = ["READ", "WRITE"]
        },
      ]
    }
  }
}
```

**Comment by alexhung** [comment]
@piotrminkina The Access API for managing Groups does not support setting `realm` or `realm_attribute` fields. Please contact your JFrog customer service person for feature request. You can mention JIRA ticket `JA-14705` for reference.

**Comment by piotrminkina** [comment]
@alexhung One thing I don't understand. As long as I use the `artifactory_group` resource, I can set values for the `realm` and `realm_attributes` properties without any problem. This works even for a fresh installation of Artifactory. I tested this for Artifactory version 7.98.9 and for Artifactory provider version 12.7.1. Unfortunately, in this version this resource is already deprecated. The moment I want to migrate to the `platform_group` resource, both the above mentioned properties become unavailable. The `terraform plan` command ends with an error with messages like “Invalid Configuration for Read-Only Attribute”.

PS: I have a license for Artifactory PRO, so I am not entitled to paid support.

**Comment by alexhung** [comment]
@piotrminkina The `artifactory_group` resource uses a different REST API from `platform_group` resource. The newer API for `platform_group` doesn't support setting `realm` or `realm_attribute` fields.

**Comment by piotrminkina** [comment]
@alexhung All clear. Thank you for the clarification.

**Comment by iamp3** [comment]
Hi @alexhung and @piotrminkina,
Has this issue been resolved in a newer version of the provider/Artifactory?
Since we need both fields in write mode for migration from the artifactory_group resource.
