### ISSUE TITLE
Produced an unexpected new value... was null.. but now cty.SetValEmpty(cty.String)

### ISSUE THREAD

**Issue by zamanh** [jfrog/terraform-provider-platform#176]
**Describe the bug**

- Running an apply with the same code again causes the diff to change (I have noticed the diff changes happen for either user or group in a similar way)

![Image](https://github.com/user-attachments/assets/c543b4d3-29f8-4945-90a5-fb5936d0a6f4)

and gives error:

```
Provider produced inconsistent result after apply Error : When applying changes to platform_group.mrgroup, provider produced an unexpected new value: This is a bug in the provider, which should be reported in the provider's own issue tracker. . members: was null, but now cty. SetVa1EmptyCcty. String) .
```

**Code snippet**
```terraform
resource "platform_group" "my-group" {
  name             = "my-group"
  description      = "My group"
  auto_join        = true
  admin_privileges = false
}

resource "artifactory_managed_user" "test-user" {
  name     = "test-user"
  password = "dcfsdcfsdc1sdcsdZ!£"
  email    = "test@rt.com"
  groups   = [platform_group.my-group.name]
}

resource "artifactory_local_generic_repository" "test-repo" {
  key          = "test-repo-2"
  description  = "Test repository"
}

resource "artifactory_remote_generic_repository" "test-repo-2-remote" {
  key          = "test-repo-2-remote"
  description  = "Test repository"
  url          = "https://test.com"
}

resource "artifactory_virtual_generic_repository" "test-repo-2-virtual" {
  key          = "test-repo-2-virtual"
  description  = "Test repository"
  repositories = [artifactory_local_generic_repository.test-repo.key, artifactory_remote_generic_repository.test-repo-2-remote.key]
}

resource "platform_permission" "my-permission" {
  name = "my-permission-name"

  artifact = {
    actions = {
      groups = [
        {
          name = platform_group.my-group.name
          permissions = ["READ", "WRITE"]
        }
      ]
    }

    targets = [
      {
        name = artifactory_local_generic_repository.test-repo.key
        include_patterns = ["**"]
      }
    ]
  }
}
```

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory: `7.98.9`
- [x] Your version of terraform: `1.9.8`
- [x] Your version of terraform provider: `1.19.0`

**Expected behavior**
- Re-running an apply against the same Terraform code shouldn't cause any diff change to either groups or users when the code has not been changed

**Comment by zamanh** [comment]
Another example of the error happening this time on a user (I am using CDKTF in this context, but still reproduced via raw TF) 

![Image](https://github.com/user-attachments/assets/c744f739-6d56-4bd5-ba86-bed8d13aa855)

Produces the same error:
![Image](https://github.com/user-attachments/assets/caefc33c-0988-4bc2-96c8-da91483ec3ac)

**Comment by alexhung** [comment]
@zamanh I'll be opening a PR with a fix to this issue shortly. However, I recommend using `ignore_changes` with `platform_group.members` attribute to avoid state drift in the first place. Because after the second `apply`, the user will be removed from the group and now `artifactory_user.groups` would have different value.
