### ISSUE TITLE
Add `platform_httpsso_settings` resource

### ISSUE THREAD

**Issue by goodtune** [jfrog/terraform-provider-platform#183]
**Is your feature request related to a problem? Please describe.**

I need to configure the HTTP SSO settings for my Edge instances, and presently that is either manually or via a Python script.

**Describe the solution you'd like**

A resource similar in nature to the `platform_saml_settings`.

```hcl
resource "platform_httpsso_settings" "this" {
  http_sso_proxied             = true
  auto_create_user             = false
  allow_user_to_access_profile = false
  remote_user_request_variable = "REMOTE_USER"
  sync_ldap_groups             = true
}
``` 

**Describe alternatives you've considered**

A Python script that I run on every deployment to bash my configuration into shape.

**Additional context**

https://jfrog.com/help/r/jfrog-rest-apis/get-http-sso-settings

**Comment by alexhung** [comment]
@goodtune Thanks for the suggestion! I've added this to our plan.
