### ISSUE TITLE
OpenID Connect Support

### ISSUE THREAD

**Issue by dejongm** [jfrog/terraform-provider-platform#38]
**Is your feature request related to a problem? Please describe.**
The provider currently does not provide an OpenID Connect resource.

**Describe the solution you'd like**
Could we get a resource to setup/deploy OpenID Connect integrations? https://jfrog.com/help/r/jfrog-platform-administration-documentation/openid-connect-integration

Thanks!

**Describe alternatives you've considered**
- continue with manual operation
- script that invokes the API using the shell provider or something like that

**Additional context**
N/A

**Comment by alexhung** [comment]
@dejongm Thank you for the request, I've added this to our road map.

**Comment by alexhung** [comment]
Dups of #26
