### ISSUE TITLE
Support Configuration of OIDC

### ISSUE THREAD

**Issue by critchtionary** [jfrog/terraform-provider-platform#39]
**Describe the solution you'd like**
It would be great if the Terraform provider supported the [OpenID Connect Integration](https://jfrog.com/help/r/jfrog-platform-administration-documentation/openid-connect-integration).

**Additional context**
There are already REST APIs for [OIDC configuration](https://jfrog.com/help/r/jfrog-rest-apis/create-or-update-oidc-configuration) and [identity mappings](https://jfrog.com/help/r/jfrog-rest-apis/create-an-identity-mapping).

**Comment by alexhung** [comment]
Dup of #26

**Comment by critchtionary** [comment]
Don't know how I missed that and the 3 other open OIDC issues 😱

Thanks.

**Comment by alexhung** [comment]
@critchtionary I moved the issue from Artifactory provider repo to this Platform provider repo 😄. This is why you didn't see these dups until now.
