### ISSUE TITLE
"Invalid token, parse" error while trying to run `terraform import`

### ISSUE THREAD

**Issue by madelaney** [jfrog/terraform-provider-platform#44]
**Describe the bug**

* Terraform  - 1.7.5 (macOS)
* Artifactory Platform provider - 1.4.1

While trying to run "terraform import"  on a `platform_permission` resource, I'm getting the following error:
```console
Error: {
  "errors" : [ {
    "code" : "UNAUTHORIZED",
    "message" : "Invalid token, parse"
  } ]
}
```

I should note that my token, that I'm passing in, has let me create repository resources so the token is value.

I've created a gist https://gist.github.com/madelaney/3ea8e36c0789fa96341b7b7dd2d89622 which should reproduce the error

**Artifatory Version**
```console
jf rt curl api/system/version | jq .version
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   975    0   975    0     0  12981      0 --:--:-- --:--:-- --:--:-- 12828
"7.71.11"
```

**Requirements for and issue**
- [X] A description of the bug
- [X] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [X] Your version of terraform
- [X] Your version of terraform provider

**Expected behavior**
I'd expect the resource to get imported but instead, I get the error.

**Additional context**

**Comment by alexhung** [comment]
@madelaney I am unable to reproduce this issue locally.

Using an admin token, I am able to import a permission from my local Artifactory instance.

```terraform
terraform {
  required_providers {
    platform = {
      source  = "jfrog/platform"
      version = "1.4.2"
    }
  }
}

provider "platform" {
  // supply JFROG_ACCESS_TOKEN as env var
}

resource "platform_permission" "my-permission" {
  name = "my-permission-name"

  artifact = {
    targets = [
      {
        name = "alexh-docker-local"
        include_patterns = ["**"]
      },
      {
        name = "ALL-LOCAL"
        include_patterns = ["**", "*.js"]
      },
      {
        name = "ALL-REMOTE"
        include_patterns = ["**", "*.js"]
      },
      {
        name = "ALL-DISTRIBUTION"
        include_patterns = ["**", "*.js"]
      }
    ]
  }
}
```

Then:

```console
terraform import platform_permission.my-permission my-permission-name
```

![Screenshot 2024-03-20 at 1 07 27 PM](https://github.com/jfrog/terraform-provider-platform/assets/27263/2d4529ef-3740-4083-ade2-e23050b9ee96)

**Comment by alexhung** [comment]
@madelaney When I use `curl` to make the API request with incorrect token, I get the expected error:

![Screenshot 2024-03-20 at 1 18 27 PM](https://github.com/jfrog/terraform-provider-platform/assets/27263/6095afde-ce46-4044-9c54-768f5cb1ce48)

**Comment by madelaney** [comment]
> I don't see the variable artifactory_access_token being set to any value in your snippet, I assume that is set somewhere. I suggest making sure that variable is set to the correct token.

The token is being passed in via `terraform.tfvars`. I also tried via setting `JFROG_ACCESS_TOKEN`, I get the same issue. 

The token _seems_ correct as the artifactory provider was happy with it when I was able to create groups / users / repositories. It's only the platform provider that seems unhappy.

**Comment by madelaney** [comment]
@alexhung , can I use the same access token for both the Artifactory and Platform provider?

**Comment by alexhung** [comment]
@madelaney Per the [REST API](https://jfrog.com/help/r/jfrog-rest-apis/create-permission), the `platform_permission` resource requires access token with admin permission. This is likely the cause of the error.

**Comment by alexhung** [comment]
@madelaney I am using a token scoped to `admin` user and did not get any error per screenshot above. I don't believe it's an issue from the provider or the resource but I also don't have any answer to your issue.

**Comment by madelaney** [comment]
@alexhung , okay, I found it.

I was using an API token that was generated from the `admin` user originally. The API token was not working with the platform `provider`. If I create an `admin` access scoped token that value works with both.

I did see that the API token was being deprecated (https://registry.terraform.io/providers/jfrog/artifactory/latest/docs#api-key-deprecated) but since the Artifactory provider, I didn't think much of it. Maybe this is a side-effect.

**Comment by alexhung** [comment]
@madelaney The API key will be deprecated by end of this year. If you are still using API key, please make plans to migrate to access tokens. Our development and testing process has been using access token since the announcement of API key deprecate in 2022(?).
