### ISSUE TITLE
`platform_permission` should replace on name change

### ISSUE THREAD

**Issue by NiklasRosenstein** [jfrog/terraform-provider-platform#64]
**Describe the bug**

This is analogous to https://github.com/jfrog/terraform-provider-artifactory/issues/944, only for the `platform_permission` resource.

**Requirements for and issue**

Terraform plans to update a `platform_permission` resource when the name changes, but the apply fails with "Not Found" (presumably attempting to do some operation on the permission's new name).

**Expected behavior**

Since a permission target cannot be renamed, it should be replaced.

**Additional context**

Example:

<img width="1099" alt="image" src="https://github.com/jfrog/terraform-provider-platform/assets/1318438/09496017-f447-4b07-b8f3-c127bf28d64e">

<img width="1081" alt="image" src="https://github.com/jfrog/terraform-provider-platform/assets/1318438/9680fddb-dae4-4db8-8d1d-1ce3320227c3">

**Comment by alexhung** [comment]
@NiklasRosenstein Thanks for the report. I've added this to our plan.
