### ISSUE TITLE
Setting `artifact.actions.groups = []` results in a perpetual diff

### ISSUE THREAD

**Issue by NiklasRosenstein** [jfrog/terraform-provider-platform#70]
**Describe the bug**

It appears that when you don't set `artifact = { actions = { groups = [] } } }` (and instead simply don't specify the attribute), it results in a permanent diff on every run.

<img width="1103" alt="image" src="https://github.com/jfrog/terraform-provider-platform/assets/1318438/8e81fc5f-df93-4e68-aa56-b0bf9dd7c537">

Provider version 1.7.2

**Comment by NiklasRosenstein** [comment]
Actually, sorry, I misread our own code.

Setting it to an empty list seems to be causing the perpetual diff.

This particular resource is defined as this, hence it does set `groups` to an empty list in certain cases and does _not_ omit the attribute as originally described.

```
resource "platform_permission" "publish" {
  for_each = local.grouped_repositories
  name     = "project-${var.project_id}-${each.key}"

  artifact = {
    targets = [
      for repo in keys(each.value.repositories) :
      {
        name             = repo
        include_patterns = local.artifactory_include_patterns_by_group_name[each.value.group_name].include_patterns
      }
    ]

    actions = {
      users = [
        {
          name        = var.artifactory_publish_users[each.value.release_type]
          permissions = [for permission in var.artifactory_permissions[each.value.release_type] : upper(permission)]
        }
      ]

      groups = (
        each.value.release_type == "playground"
        ? [
          for group in var.artifactory_developer_groups :
          {
            name        = group
            permissions = ["READ", "WRITE", "ANNOTATE", "DELETE", "MANAGE"]
          }
        ]
        : []
      )
    }
  }
}
```

**Comment by alexhung** [comment]
@NiklasRosenstein Thanks! I've added to our plan to investigate.
