### ISSUE TITLE
platform_oidc_configuration resource docs slighting misleading with trailing slash for issuer_url

### ISSUE THREAD

**Issue by StephenWithPH** [jfrog/terraform-provider-platform#85]
**Describe the bug**
This is related to #71, and it is *purely* a documentation nit.

Currently, the docs for `platform_oidc_configuration` include an example resource that uses GitHub's issuer url. In that example, the url still has a trailing slash:

https://github.com/jfrog/terraform-provider-platform/blob/424c56ffbee53f8e439b08ed446abb3eaf3165be/docs/resources/oidc_configuration.md#L19

**Comment by alexhung** [comment]
@StephenWithPH Thanks for the report! I'll update the doc.

**Comment by alexhung** [comment]
@StephenWithPH The fix will be published in the next release.
